#!/bin/bash

for size in 1K 64K 1M 16M 64M
do 
	for threads in 1 4 16 32 64 128
	do
		 echo $size, $threads >> ./results.log
		 rados bench -p .rgw.buckets 60 write -b $size -t $threads | grep -i 'bandwidth\|latency' >> ./results.log
	done
done
		
